Pipeline configuration with localstack and terrafom

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,4 +1,4 @@
-name: CI/CD Pipeline - Kubernetes Infra
+name: CI/CD Pipeline - Full Integration
 
 on:
   push:
@@ -8,24 +8,108 @@ on:
     branches:
       - main
 
+permissions:
+  contents: write
+  pull-requests: write
+  issues: write
+  repository-projects: write
+
 jobs:
-  update-k8s:
+  build-deploy:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Check out infra-k8s repo
-        uses: actions/checkout@v3
+      - name: Check out code
+        uses: actions/checkout@v2
+
+      - name: Set permissions for Gradle Wrapper
+        run: chmod +x ./gradlew
+
+      - name: Set up JDK
+        uses: actions/setup-java@v2
+        with:
+          distribution: 'adopt'
+          java-version: '17'
+
+      - name: Build with Gradle
+        run: ./gradlew build --no-daemon
+
+      - name: Build Docker image
+        run: docker build -t gabiponcet/lanchonete-app:latest .
+
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v1
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Push Docker image
+        run: docker push gabiponcet/lanchonete-app:latest
+
+      - name: Test GITHUB_TOKEN permissions
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          echo "Testing GITHUB_TOKEN permissions"
+          curl -H "Authorization: token $GITHUB_TOKEN" \
+               -H "Accept: application/vnd.github.v3+json" \
+               https://api.github.com/repos/gabiponcet/infra-k8s/contents/
+
+      - name: Clone Kubernetes repo
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/gabiponcet/infra-k8s.git k8s
+          cd k8s
+
+      - name: Copy Terraform files
+        run: |
+          mkdir -p k8s/Terraform
+          cp -R k8s/Terraform/* k8s/Terraform/
+          if [ -f k8s/Terraform/lambda_function_payload.zip ]; then
+            cp k8s/Terraform/lambda_function_payload.zip k8s/Terraform/lambda_function_payload.zip
+          else
+            echo "File lambda_function_payload.zip not found"
+            exit 1
+          fi
+
+      - name: Install Terraform
+        run: |
+          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
+          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
+          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
+          sudo apt-get update && sudo apt-get install -y terraform
+
+      - name: Install LocalStack CLI
+        run: pip install localstack
+
+      - name: Start LocalStack with Docker
+        run: |
+          export LAMBDA_EXECUTOR=docker
+          localstack start -d
+        env:
+          LAMBDA_EXECUTOR: docker
+
+      - name: Initialize Terraform
+        run: terraform init
+        working-directory: k8s/Terraform
+
+      - name: Apply Terraform
+        run: terraform apply -auto-approve
+        working-directory: k8s/Terraform
 
       - name: Update Kubernetes manifests
         id: update_manifests
         run: |
           find ./k8s -name 'deployment.yaml' -exec sed -i 's|image:.*|image: gabiponcet/lanchonete-app:latest|' {} +
           git diff --quiet || echo "::set-output name=changes_detected::true"
-      - name: Commit and push changes to infra-k8s repo
+
+      - name: Commit and push changes to Kubernetes repo
         if: steps.update_manifests.outputs.changes_detected == 'true'
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
+          cd k8s
           git config --global user.email "gabiponcet@gmail.com"
           git config --global user.name "gabiponcet"
           git add .
